-- ⚠️  Apply against the LEAD-ENGINE Supabase project.
--
-- 1. contact_channels — the deep-enrichment scraper now collects EVERY
--    contact path it finds on the lead's website (homepage + impressum
--    + kontakt page): all emails, all phone numbers, socials. Each entry
--    is tagged with how likely it funnels directly to the owner:
--      [{ type: 'email'|'phone'|'instagram'|'facebook'|'linkedin',
--         value, label, owner_likelihood: 'high'|'medium'|'low' }]
--
-- 2. offer_benefits — 3 short customer-benefit key facts for the
--    fit_offer, generated by the scorer ("was bringt dem Kunden das"),
--    shown as the offer block under the pain points + available as
--    Smartlead merge tags.

alter table public.leads
  add column if not exists contact_channels jsonb,
  add column if not exists offer_benefits text[];
