-- ⚠️  Apply against the LEAD-ENGINE Supabase project.
--
-- Lead-detail view for live owner conversations:
--   sales_points — 3 short business-case angles (why the owner should
--                  invest), generated by the scorer. Shown as a block.
--   prep_qa      — AI-generated meeting prep: questions the owner will
--                  almost certainly raise + your answers. [{q, a}].
--                  Generated on demand from the lead detail page.

alter table public.leads
  add column if not exists sales_points text[],
  add column if not exists prep_qa jsonb;
